Init User Controler & Repository Tests

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -8,8 +8,9 @@ on:
 
 
 jobs:
-  default:
-    name: Scan, Build, and Push Docker Image
+
+  qodana-scan:
+    name: Scan Qodana
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -17,7 +18,49 @@ jobs:
       checks: write
 
     steps:
+      - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
+          fetch-depth: 0  # a full history is required for pull request analysis
+      - name: 'Qodana Scan'
+        uses: JetBrains/qodana-action@v2023.3
+        env:
+          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
 
+  run-tests:
+    name: Run Tests
+    runs-on: ubuntu-latest
+    steps:
+        - name: Checkout code
+          uses: actions/checkout@v4
+          with:
+            ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
+            fetch-depth: 0  # a full history is required for pull request analysis
+
+        - name: Set up JDK 21
+          uses: actions/setup-java@v4
+          with:
+            distribution: 'corretto'
+            java-version: 21
+
+        - name: Run Tests
+          run: |
+            mvn clean
+            mvn test
+
+        - name: Test Report
+          uses: dorny/test-reporter@v1
+          if: success() || failure()    # run this step even if previous step failed
+          with:
+            name: Junit Tests            # Name of the check run which will be created
+            path: reports/junit-*.xml    # Path to test results
+            reporter: java-junit        # Format of test results
+
+
+  docker-build-push:
+      name: Build and Push Docker Image
+      runs-on: ubuntu-latest
+      steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: "Checkout code"
         uses: actions/checkout@v4
@@ -32,19 +75,6 @@ jobs:
           distribution: 'corretto'
           java-version: 21
 
-      - name: Set PostgresSQL
-        uses: harmon758/postgresql-action@v1
-        with:
-          postgresql version: '15'
-          postgresql db: ${{ secrets.POSTGRES_DB }}
-          postgresql user: ${{ secrets.POSTGRES_USERNAME }}
-          postgresql password: ${{ secrets.POSTGRES_PASSWORD }}
-
-      - name: 'Qodana Scan'
-        uses: JetBrains/qodana-action@v2023.3
-        env:
-          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
-
       - name: "Build application"
         env:
           PROFILE: prod
@@ -57,7 +87,10 @@ jobs:
           ADMIN_ACCOUNT_PASSWORD: ${{ secrets.ADMIN_ACCOUNT_PASSWORD }}
         run: |
           mvn clean
-          mvn -B package --file pom.xml
+          mvn -B package -Dmaven.test.skip --file pom.xml
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
@@ -65,7 +98,7 @@ jobs:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Docker Build and Push
+      - name: Build and Push Docker Image
         uses: docker/build-push-action@v5
         with:
           context: .
